apiVersion: v1
kind: Pod
metadata:
  name: print-env-greeting
spec:
  containers:
  - name: env-container
    image: bash
    env:
    - name: GREETING
      value: "Welcome to"
    - name: COMPANY
      value: "DevOps"
    - name: GROUP
      value: "Industries"
    command: ["bash", "-c", "echo \"$GREETING $COMPANY $GROUP\""]
