apiVersion: v1
kind: Pod
metadata:  
  name: yellow
spec:
  containers:
    - name: lemon
      image: busybox
      command: ["sleep", "120"]  # Keeps the container running
    - name: gold
      image: redis
      ports:
        - containerPort: 6379  # Default Redis port
